### ISSUE TITLE
License of the FAQ

### ISSUE THREAD

**Issue by pathumego** [theleagueof/licenses#2]
@micahbrich how is the contents of this repo licensed? I find it the FAQ very useful and would like to use it on few other places with edits; if license allows.

**Comment by alerque** [comment]
The license and FAQ themselves were [developed by SIL](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL#83afb016). Any inquires about this should be directed towards them, not us.

That being said off the top of my head I'm pretty sure you could include whatever changes you liked, but you might have to call the license something other than "OFL 1.1". It's possible you could tweak the FAQ without in effect making a different license, but I'm not sure.
